name = "wasm-worker"
type = "rust"
account_id = "ecddfd943e72c641c99a5f6fabe352b1"
workers_dev = true

[env.production]
# The ID of the domain to deploying to
zone_id = "fd9232c4e13140ff102436229b17b198"

# The route pattern your Workers application will be served at
route = "kicks.fan/*"